### ISSUE TITLE
ValueError: cannot set WRITEABLE flag to True of this array

### ISSUE THREAD

**Issue by fbessho** [fbessho/PyPoi#25]
With numpy==1.16.2, the following exception occurs when blending images.

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/besshf/anaconda3/envs/pypoi/lib/python2.7/lib-tk/Tkinter.py", line 1547, in __call__
    return self.func(*args)
  File "/Users/besshf/src/PyPoi/pypoi/gui.py", line 179, in blend
    src.flags.writeable = True
ValueError: cannot set WRITEABLE flag to True of this array
```

This error is reproducible by 

```
from PIL import Image
import numpy as np

print(np.__version__)  # 1.16.2

# https://github.com/fbessho/PyPoi/raw/v0.2.1/pypoi/testimages/test1_src.png
path = 'pypoi/testimages/test1_src.png'
image = Image.open(path)

array = np.asarray(image)
array.flags.writeable = True
```

**Comment by fbessho** [comment]
Using `np.array` instead of `np.asarray` resolves the issue.

REF: https://stackoverflow.com/a/54308748/870658
